### PR TITLE
#176-setting user image on home fragment

### LINKED ISSUE #176: 홈 화면 유저 정보 이미지 연동
### You want to:

* [ ] report a *bug*
* [x] request a *feature*
* [ ] request an update to the documentation
* [ ] requeset a code change that improves performance
* [ ] request other

### Current behaviour

*What is actually happening?*

### Expected behaviour

*What is expected?*
* 현재 기본으로 설정되어 있는 이미지를 실제 유저 정보 이미지로 변경

### PR DESCRIPTION
**Pull request by ro0opf**
### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### New behaviour
* glide binding image 부분을 util로 이동
* 홈 화면 image 바인딩

### Other information (e.g. related issues)
resolved #176

### CODE REVIEW

**Review by wjddnwls918 — APPROVED** [review]
LGTM

File: app/src/main/java/com/teamdonut/eatto/common/Binding.java [hunk 1]
```diff
@@ -1,11 +1,22 @@
...
+import com.teamdonut.eatto.common.util.GlideApp;
 
 public class Binding {
     @BindingAdapter("adapter")
-    public static void bindAdapter(RecyclerView recyclerView, RecyclerView.Adapter<?> adapter) {
+    public static void setAdapter(RecyclerView recyclerView, RecyclerView.Adapter<?> adapter) {
         recyclerView.setAdapter(adapter);
     }
+
+    @BindingAdapter({"glideImage", "glideError"})
```
Comment (Zi-Yun) [inline app/src/main/java/com/teamdonut/eatto/common/Binding.java]: 속성이름을 조금더 범용적인 느낌으로 바꾸면 좋을것 같아요.

**Review by Zi-Yun — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/teamdonut/eatto/common/Binding.java (hunk 1 above)
Comment (ro0opf) [reply app/src/main/java/com/teamdonut/eatto/common/Binding.java]: 수정했습니다
baa6f95

**Review by Zi-Yun — APPROVED** [review]
