### PR TITLE
#187-맵 검색 화면에 키워드 힌트 추가

### LINKED ISSUE #187: 맵 검색 화면 hint 자기 위치기반으로 보여주기
### You want to:

* [ ] report a *bug*
* [x] request a *feature*
* [ ] request an update to the documentation
* [ ] requeset a code change that improves performance
* [ ] request other

### Current behaviour

*What is actually happening?*

### Expected behaviour

*What is expected?*
* 맵 검색 화면 hint 자기 위치기반으로 보여주기

### PR DESCRIPTION
**Pull request by ro0opf**
### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### New behaviour
* 맵 검색 화면에 키워드 힌트 추가

### Other information (e.g. related issues)
image

resolved #187

### CODE REVIEW

File: app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java [hunk 1]
```diff
@@ -68,12 +63,9 @@ public BoardViewModel(BoardNavigator navigator) {
         mNavigator = navigator;
     }
 
-    public void getEtKeywordHint(Context context) {
+    public void fetchEtKeywordHint(String kakaoKey, String longtitude, String latitude, String defaultAddress) {
         disposables.add(
```
Comment (wjddnwls918) [inline app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java:67]: 👍

**Review by wjddnwls918 — APPROVED** [review]
LGTM

**Review by Zi-Yun — APPROVED** [review]
LGTM
