### PR TITLE
#256-custom marker

### LINKED ISSUE #256: Map custom marker 생성
### You want to:

* [ ] report a *bug*
* [x] request a *feature*
* [ ] request an update to the documentation
* [ ] requeset a code change that improves performance
* [ ] request other

### Current behaviour

*What is actually happening?*

### Expected behaviour

*What is expected?*
* custom marker 생성

### PR DESCRIPTION
**Pull request by ro0opf**
### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### New behaviour
* custom marker 생성

### Other information (e.g. related issues)
resolved #256

### CODE REVIEW

File: app/src/main/java/com/teamdonut/eatto/ui/map/MapFragment.java [hunk 1]
```diff
@@ -132,7 +138,7 @@ public void startLocationUpdates() {
                 }, throwable -> {
```
Comment (Zi-Yun) [inline app/src/main/java/com/teamdonut/eatto/ui/map/MapFragment.java]: 이 부분을 예전에 맞췄던대로 `e ->`로 통일하면 어떨까요?

**Review by Zi-Yun — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/teamdonut/eatto/ui/map/MapFragment.java (hunk 1 above)
Comment (ro0opf) [reply app/src/main/java/com/teamdonut/eatto/ui/map/MapFragment.java]: 수정했습니다
dee40ba

**Review by Zi-Yun — APPROVED** [review]
