### PR TITLE
#129-change retrofit singleton

### LINKED ISSUE #129: retrofit singleton 변경
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

*What is actually happening?*

### Expected behaviour

*What is expected?*
* retrofit singleton 객체로 변경
* kakao retrofit 생성

### PR DESCRIPTION
**Pull request by ro0opf**
### The kind of change this PR does introduce

* [ ] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [x] a code change that improves performance
* [ ] other

### New behaviour
* retrofit lazy holder 방식으로 변경 (singleton)
* Kakao retrofit 추가

### Other information (e.g. related issues)

resolved #129

### CODE REVIEW

File: app/src/main/java/com/teamdonut/eatto/model/ServiceGenerator.java [hunk 1]
```diff
@@ -20,15 +21,36 @@ private static OkHttpClient getClient() {
...
+        private static Retrofit createInstance(String url) {
+            return new Retrofit.Builder()
+                    .baseUrl(url)
+                    .client(getClient())
+                    .addConverterFactory(GsonConverterFactory.create())
+                    .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
+                    .build();
+        }
+
+        private static final Retrofit INSTANCE = createInstance(BASE_URL);
```
Comment (Zi-Yun) [inline app/src/main/java/com/teamdonut/eatto/model/ServiceGenerator.java]: 변수를 최상단에 선언하면 좋을것같아요.

**Review by Zi-Yun — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/teamdonut/eatto/model/ServiceGenerator.java (hunk 1 above)
Comment (ro0opf) [reply app/src/main/java/com/teamdonut/eatto/model/ServiceGenerator.java]: 수정했습니다.
b071f11

**Review by wjddnwls918 — APPROVED** [review]
LGTM

**Review by Zi-Yun — APPROVED** [review]
