### PR TITLE
#47-my page fragment layout

### LINKED ISSUE #47: 마이페이지 화면 레이아웃 생성
### You want to:

* [ ] report a *bug*
* [x] request a *feature*

### Current behaviour

*What is actually happening?*

### Expected behaviour
*What is expected?*

* 마이페이지 레이아웃 생성
image

### PR DESCRIPTION
**Pull request by ro0opf**
### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### New behaviour
* left,right Coding conventions에 맞게 수정
* Mypage fragment, viewmodel, xml 생성

image

### Other information (e.g. related issues)

resolved #47

### CODE REVIEW

File: app/src/main/java/com/teamdonut/eatto/ui/mypage/MypageViewModel.java [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package com.teamdonut.eatto.ui.mypage;
+
+import androidx.lifecycle.ViewModel;
+
+public class MypageViewModel extends ViewModel {
+    // TODO: Implement the ViewModel
```
Comment (wjddnwls918) [inline app/src/main/java/com/teamdonut/eatto/ui/mypage/MypageViewModel.java:6]: 저희 ViewModel 사용하기로 했었나요 ??

Comment (Zi-Yun) [reply app/src/main/java/com/teamdonut/eatto/ui/mypage/MypageViewModel.java:6]: 네

**Review by Zi-Yun — APPROVED** [review]
